[package]
name = "mucuroso"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
garmin_gym_fit_parser = { version = "0.1.0", path = "../garmin_gym_fit_parser" }
serde = { version = "1.0.219", features = ["derive"] }
