[package]
name = "garmin_gym_fit_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["serde"], default-features = false }
csv = "1.3.1"
fitparser = "0.9.0"
serde = "1.0.219"
uuid = { version = "1.17.0", features = ["serde"] }
